# Generated by Django 5.0.13 on 2025-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
    ]
