# Generated by Django 5.0.13 on 2025-03-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='Type',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
