# Generated by Django 5.0.13 on 2025-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_ai', '0002_register_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='Password',
            field=models.CharField(max_length=300),
        ),
    ]
